---
- name: Setup DHCP on ethernet interface(s) and timedatectl timezone
  hosts: localhost
  vars:
    timezone: America/New_York

  tasks:
    - name: List ethernet interfaces
      ansible.builtin.set_fact:
        eths: |
          {{
              lookup(*(["vars"] +
                       ansible_facts.interfaces |
                       map("regex_replace", "^(.+)$", "ansible_\1"))) |
              community.general.json_query("[?type=='ether'].device") |
              sort
          }}

    - name: Print ethernet interfaces
      ansible.builtin.debug:
        var: eths

    - name: Create the netplan file
      # See
      # https://documentation.ubuntu.com/server/explanation/networking/configuring-networks/#dynamic-ip-address-assignment-dhcp-client
      become: true
      ansible.builtin.template:
        src: templates/99_config.yaml.j2
        dest: /etc/netplan/99_config.yaml
        mode: "0700"
      notify: Apply netplan

    - name: Set timezone
      become: true
      community.general.timezone:
        name: |-
          {{ timezone }}
        hwclock: UTC
      notify: Restart cron

  handlers:

    - name: Apply netplan
      become: true
      ansible.builtin.command: netplan apply --debug
      # The systemctl command will fail in a non-podman container.
      when: ansible_virtualization_type != "docker"

    - name: Restart cron
      become: true
      ansible.builtin.systemd:
        name: cron
        state: restarted
