---
- name: Install system software
  hosts: localhost

  tasks:
    - name: Install system software
      become: true
      ansible.builtin.apt:
        pkg:
          - build-essential
          - emacs-nox
          - gfortran
          - parallel
          - patchelf
          - pax-utils
          - stow
