---
- name: Install system software
  hosts: localhost

  tasks:
    - name: Install system software
      become: true
      ansible.builtin.apt:
        pkg:
          - build-essential
          - datamash
          - emacs-nox
          - gfortran
          - libtree
          - parallel
          - patchelf
          - stow
          - unzip
          - zip
