---
- name: Create users and import GitHub public keys
  hosts: localhost
  vars:
    users:
      # Several IT people / GitHub accounts can be associated with the
      # single ssoelocal user, therefore the github key is a list.
      - comment: SSoE IT
        name: ssoelocal
        github: []
      # Arrange lab members in alphabetical order.
      - comment: Jason Shoemaker
        name: jas518
        github:
          - jshoe1984
      - comment: Lauren Nichols
        name: lan120
        github:
          - laurenmnichols
      - comment: Pariksheet Nanda
        name: pan79
        github:
          - omsai
      - comment: Ramakrishna Suresh
        name: ras365
        github:
          - Salty-Ramen
      - comment: Tatum Liparulo
        name: tam193
        github:
          - tam193

  tasks:
    - name: Create home directory
      become: true
      ansible.builtin.user:
        name: |-
          {{ item.name }}
        comment: |-
          {{ item.comment }}
        generate_ssh_key: true
        groups:
          # Server default groups.
          - adm
          - sudo
          - dip
          - cdrom
          - plugdev
          - lxd
        shell: /bin/bash
      loop: |
        {{ users }}

    - name: Flatten list for merging GitHub keys
      ansible.builtin.set_fact:
        name_github: |
          {{
              users |
              community.general.json_query("[:].name") |
              flatten2d(users |
                        community.general.json_query("[:].github"))
          }}

    - name: Show user-github pairs
      ansible.builtin.debug:
        var: name_github

    - name: Import GitHub public keys
      become: true
      ansible.posix.authorized_key:
        user: |-
          {{ item[0] }}
        key: |-
          https://github.com/{{ item[1] }}.keys
      loop: |
        {{ name_github }}
